import { Toaster } from 'sonner';
import "../../styles/meeting.globals.css";
// import "/styles/globals.css";
// import AppBar from '../components/layout/AppBar';
// import Footer from '../components/layout/Footer';
// import LayoutWrapper from '../LayoutWrapper';


require("@solana/wallet-adapter-react-ui/styles.css");

export const metadata = {
  title: 'BUILDERZ Solana dApp Scaffold',
  description: 'Generated by Next.js',
};

export default async function RootLayout({ children }) {

  return (
    // <LayoutWrapper >
      <html lang="en">
         {/* <body> */}
          {/* <AppBar /> */}
          <div className={`min-h-screen`}>
            {children}
          </div>
          {/* <Footer /> */}
          <Toaster position="bottom-right" />
        {/* </body> */}
      </html>
    // </LayoutWrapper>
  );
}



// import { Inter } from "next/font/google";
// import "/styles/meeting.globals.css";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
